FROM golang:1.25-alpine AS build
ARG VERSION="dev"
ARG BUILD_TIME="unknown"

# Set the working directory
WORKDIR /build

# Install git
RUN --mount=type=cache,target=/var/cache/apk \
    apk add git

# Copy source code
COPY . .

# Build the AI agent
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 go build -ldflags="-s -w -X main.version=${VERSION} -X main.commit=$(git rev-parse HEAD) -X main.date=${BUILD_TIME}" \
    -o /bin/aiagent ./cmd/aiagent

# Make a stage to run the app
FROM gcr.io/distroless/base-debian12@sha256:937c7eaaf6f3f2d38a1f8c4aeff326f0c56e4593ea152e9e8f74d976dde52f56

# Set the working directory
WORKDIR /app

# Copy the binary from the build stage
COPY --from=build /bin/aiagent .

# Expose the AI Agent port
EXPOSE 8186

# Run as nonroot user
USER nonroot:nonroot

# Set the entrypoint to the AI agent binary
ENTRYPOINT ["/app/aiagent"]

# Made with Bob